easy_admin:
  entities:
    Ville:
      class: App\Entity\Ville
      form: 
        fields:
          - { property: 'title' }
      list:
        actions:
          - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}

